### ISSUE TITLE
ignore files in logseq directory

### ISSUE THREAD

**Issue by pwright** [viktomas/logseq-export#2]
After exporting using this tool (which is great), I found a logseq page that should be deleted.
So, I delete it and export again... but the file is still exported, because logseq placed the deleted file in `logseq/.recycle`.

Can the tool ignore all contents of logseq directory, given that this directory could also contain  backups?

**Comment by viktomas** [comment]
That makes sense. It's going to be relatively easy to implement so I'll do it :)

@pwright Do you think it is OK if I ignore the whole `logseq` folder?

**Comment by viktomas** [comment]
I released version `0.0.2`, which ignores the `logseq` folder :+1:

**Comment by pwright** [comment]
+1 to ignoring all `logseq` folder, and thanks!
