### ISSUE TITLE
feature request: image folder

### ISSUE THREAD

**Issue by youkq95** [viktomas/logseq-export#6]
This is a great tool! Would it be possible to put the images in the same folder with the md files(together within an individual folder)?

**Comment by viktomas** [comment]
I'm glad you like this project @youkq95, can you please write in more detail about your use case?

Ideally, I would love to find a way how to make the `logseq-exporter` work generally for these use cases rather than add boolean flags to completely change behaviour.

**Comment by youkq95** [comment]
I am currently using `logseq-exporter` to convert logseq pages to hugo blog posts. The current version works fine. But in some cases(see below, from [here](https://github.com/CaiJimmy/hugo-theme-stack/tree/master/exampleSite/content)), the md file and the figures are put under the same folder named using the page title. I think it would be more convenient to manage each post. I am not familiar with `go` so may be it would be too complicated ?🤪
```
post
    ├── chinese-test # this is the post title
    │   ├── florian-klauer-nptLmg6jqDo-unsplash.jpg # these are the figs that referred in the index.md file
    │   ├── helena-hertz-wWZzXlDpMog-unsplash.jpg
    │   ├── hudai-gayiran-3Od_VKcDEAA-unsplash.jpg
    │   ├── index.zh-cn.md # this is the md file that contains the main content
    │   └── luca-bravo-alS7ewQ41M8-unsplash.jpg
    ├── markdown-syntax
    │   ├── index.md
    │   └── pawel-czerwinski-8uZPynIu-rQ-unsplash.jpg
```

**Comment by viktomas** [comment]
@youkq95 I reworked the `logseq-export` to be more universal. Now the images get always exported to `/logseq-assets` folder and it's up to the import script to move the images to the right place

https://github.com/viktomas/logseq-export/blob/main/import_to_hugo.sh#L34-L53

Let me know if you'd like any help with customising the script for your needs :+1:
